### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by tomv79** [OpenAstroTech/OpenAstroTracker#14]
The left button does not switch throught the menues.
It has the same effect as the down button.
Sometimes the left button switches the menue.

**Comment by OpenAstroTech** [comment]
Go to the second tab of the code "a_inits" and find line 36 "if (adc_key_in < 600)  return btnLEFT;"

Try if changing the value in that line to 700 or 800 fixes it

**Comment by tomv79** [comment]
Yes the left button now works.
But the select button seem to be the left now.

**Comment by OpenAstroTech** [comment]
Try increasing its value in the code till it works

**Comment by tomv79** [comment]
I have make following changes that works for me well!!

if (adc_key_in > 1000) return btnNONE;
  if (adc_key_in < 20)   return btnRIGHT;
  if (adc_key_in < 150)  return btnUP;
  if (adc_key_in < 300)  return btnDOWN;
  if (adc_key_in < 500)  return btnLEFT;
  if (adc_key_in < 700)  return btnSELECT;

now the keys works fine!

**Comment by OpenAstroTech** [comment]
Great! I'll mention this in the upcoming troubleshooting guide, i think some of the LCDs need different values.

Gonna close this
