### ISSUE TITLE
Bubble level holder diameter is 65mm but shopping list linked item is 60mm in diameter.

### ISSUE THREAD

**Issue by JJ-White** [OpenAstroTech/OpenAstroTracker#151]
I've ordered the bubble level straight through the Aliexpress link on the shopping list page (https://wiki.openastrotech.com/en/OpenAstroTracker/ShoppingList) and now that I've printed the holder I find out that the holder is made for a bubble level with a diameter of 65mm. The shopping list itself still lists the 65mm version but maybe the listing itself changed? I'll probably hot glue it in for now as the level can be stuck through the smaller hole but won't stay in place.

Could someone make an updated model for the 60mm version, as I can assume more people have bought this version?

**Comment by intercipere** [comment]
Hey, i added a holder for 60mm bubble levels

https://github.com/OpenAstroTech/OpenAstroTracker/blob/master/STL/2020%20Base/b2_level%20holder_60mm.STL
