### ISSUE TITLE
All latitude working

### ISSUE THREAD

**Issue by RY295** [OpenAstroTech/OpenAstroTracker#159]
Hi,  I live in bortle 9 skies and will travel to different dark places for astrophotography. I want  to use OAT with guiding, will it make a difference if I choose a 30 degree latitude or its mandatory that I make all latitude mod in OAT. I couldnt understand the modification required for all latitude instead of a fixed latitude say 30 degree. looking for help.
Thanks

**Comment by ClutchplateDude** [comment]
I would print it for the highest latitude you expect to visit. Then for lower latitudes you will need to prop up the rear of the OAT by the difference between the highest and the current latitude.

You should pose questions like this in our Discord Questions forum, lots of people available to help there.
