### ISSUE TITLE
BUG : RASteps not being correctly converted to float in c_buttons.ino

### ISSUE THREAD

**Issue by EorEquis** [OpenAstroTech/OpenAstroTracker#16]
Current line 8 is 
`onehour = (float(RAsteps / 288)) * RevSteps;`

Which leave RASteps as an int  (this produces /u/mxpwr60's comment that 288 is the "lower limit" as seen [here](https://old.reddit.com/r/OpenAstroTech/comments/fmiwwz/calibration/), since dividing any int < 288 by 288 returns 0.

It also results in the RA Rate being impossible to set as described in the setup/calibration instructions, since only RASteps values that are multiples of 288 (288, 576, etc) will produce any change in the value of onehour.

I believe code should be
`onehour = (float(RAsteps) / 288) * RevSteps;`

Have made this change in my mount, and see RA calibration results as expected.

**Comment by OpenAstroTech** [comment]
forgot to close it
