### ISSUE TITLE
V1.6 not compiling

### ISSUE THREAD

**Issue by raminnobari** [OpenAstroTech/OpenAstroTracker#26]
![OpenAstroTracker](https://user-images.githubusercontent.com/49766409/79520780-dad31c80-8057-11ea-8836-844ba2fec08f.jpg)
V1.6. not compiling properly. Errors are located in "d-calulation" and "f-printout" files.
I have no issues with v1.4.5 ...

Am I doing something wrong ?!

**Comment by raminnobari** [comment]
1.6.25 compiles just fine. "d-calulation" and "f-printout"  are already gone.

**Comment by OpenAstroTech** [comment]
There were accidentally some wrong files in the initial upload for 1.6.25. I reuploaded the code, it should work now with the latest release

**Comment by raminnobari** [comment]
perfect
