### ISSUE TITLE
GoTo not working for negative DEC

### ISSUE THREAD

**Issue by StandaB** [OpenAstroTech/OpenAstroTracker#30]
Navigating to POI M42 Orion nebula moves OAT to DEC 90°22' instead of -5°22'. It seems that in _struct PointOfInterest_ using "byte degreeDEC;" is problematic since _byte_ is unsigned. Using _int degreeDEC_ solved this for me

nice project though. I made a slight modification to use A4988 stepper drivers with microstepping to see if it is possible to have smoother tracking. Just waiting for a clear sky now :)

**Comment by andre-stefanov** [comment]
Thx! Fixed in e4f2c06743984873fc060b9975149918a24d1c0c
