### ISSUE TITLE
Sync not working for RA

### ISSUE THREAD

**Issue by jwellman80** [OpenAstroTech/OpenAstroTracker#31]
When a Sync is issued from an ASCOM client the RA is not getting synced correctly.  

Observed: 
1. Sync RA/Dec Values
2. Dec value returned from device is correct
3. RA value is "seemingly random" but certainly not the passed in value for the sync
4. Sync RA/Dec values again
5. Dec is still correct
6. RA reverts to the pre-sync RA (basically seems to return to the value prior to the initial sync)

Sending subsequent syncs to the same RA/Dec will bounce the RA between the "pre sync RA" and the RA from 3 above.

Expected:
-Sync RA/Dec values
-RA/Dec values returned are the same or very close to synced values

Logs: 
Sync multiple syncs to same coordinates starts here:
12:13:13.541 SyncToCoordinates         RA 4.31251321778479, Dec 57.9046880388334

[ASCOM.OpenAstroTracker.LocalServer.1212.135460.txt](https://github.com/OpenAstroTech/OpenAstroTracker/files/4541091/ASCOM.OpenAstroTracker.LocalServer.1212.135460.txt)

**Comment by ClutchplateDude** [comment]
This is fixed in V1.6.54a
