### ISSUE TITLE
Assemply instructions

### ISSUE THREAD

**Issue by crami** [OpenAstroTech/OpenAstroTracker#4]
Hi
Could you probably post some assembly instructions or some close-up Photos of your assembled OpenAstroTracker to make assembly easier?

Thanks
  Matthias

**Comment by threalboss** [comment]
He is currently working on revising the build guide. Keep up to date on r/openastrotech https://www.reddit.com/r/OpenAstroTech/

**Comment by OpenAstroTech** [comment]
have been added
