### ISSUE TITLE
Compiling under Ubuntu linux fails

### ISSUE THREAD

**Issue by theoracle09** [OpenAstroTech/OpenAstroTracker#63]
Reddit post: https://www.reddit.com/r/OpenAstroTech/comments/icf009/compiling_errors_in_arduino_ide/

Compiling version 1.8.12 under Ubuntu Linux causes errors due to Linux discriminating against upper and lower case in the include statements. Apparently Windows doesn't care if the file is named "Configuration_pins.hpp" or "configuration_pins.hpp", but Linux does. 

I'll be submitting a pull request for this issue shortly. 

**Apparently I've forgotten how to run git, so I won't be submitting a pull request. Regardless, here are the files that I updated to make this compile on Ubuntu:

a_inits.hpp: Line 5, #include "Configuration_pins.hpp"
c72_menuHA.hpp: Line 3, #include "Configuration_adv.hpp"
c72_menuHA.hpp: Line 4, #include "Configuration_adv.hpp"
                               Line 5, #include "Configuration_pins.hpp"

With those changes I was able to compile just fine under Ubuntu Linux.

**Comment by OpenAstroTech** [comment]
Thanks! Changes added to develop branch
