### ISSUE TITLE
Wrong Serial interface for DEC?

### ISSUE THREAD

**Issue by stone17** [OpenAstroTech/OpenAstroTracker#68]
https://github.com/OpenAstroTech/OpenAstroTracker/blob/d383d151e34142fe88fd5ae8a6d664c53c0af1c6/Software/Arduino%20code/OpenAstroTracker/Configuration_pins.hpp#L37

This should be Serial2?

My DEC motor doesnt work properly if this is set to Serial3.

**Comment by pay4nothing** [comment]
Hi @Stone17,

thank you for your comment. I just had a weird behavor of the DEC axis with slipping and non holding the position. I fixed this to Serial2 and my problem was solved. So thank you!

**Comment by andre-stefanov** [comment]
@ClutchplateDude this really looks like a type. I just wonder why it did not cause issues for e.g. @OpenAstroTech since the this change was done 3 months ago with [v1.8.02](https://github.com/OpenAstroTech/OpenAstroTracker/commit/308a0b3f82951cc9539fa4a7019a85a127707cfb)

**Comment by pmneo** [comment]
RA and DEC can be both on Serial3. The have different adresses: 0b00 for RA (with MS0 = LOW and MS1 = LOW) and 0b01 for DEC (with MS0 HIGH and MS1 LOW) (https://wiki.openastrotech.com/wiki/NEMA_Wiring#TMC2209)

CS

**Comment by andre-stefanov** [comment]
The issue was fixed by adapting the comment. Be aware that the most recent version of this file looks different because it is using separate pin number definitions now (to also allow SoftwareSerial).
