### ISSUE TITLE
[Arduino] Configure NEMA pins for ESP32

### ISSUE THREAD

**Issue by ClutchplateDude** [OpenAstroTech/OpenAstroTracker#79]

**Comment by chatainsim** [comment]
Hello,
Is the ESP32+NEMA code release yet ? Or do we have tu use arduino mega/uno for now with the nema motor ?

Thanks

**Comment by andre-stefanov** [comment]
Esp32 already supports nemas on develop branch. Uno was removed from supported devices due to low memory.
